sudo: false
language: node_js

node_js:
  - '5'
  - '6'

install:
  - 'npm install'
  - 'npm run get-started'

script:
  - 'npm run lint'
  - 'npm test'
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
